### ISSUE TITLE
Empty checks, all sites bad

### ISSUE THREAD

**Issue by DaKnOb** [gutworth/httpswatch#12]
Just ran ```python3.2 check_https.py``` (after completely commenting out all ```jinja2``` lines) and the result in ```cache.json``` has all sites reported as ```bad``` and all ```checks``` empty. 
The logs do not report a DNS failure. Any ideas?

**Comment by alex** [comment]
I suspect this requires Python3.4, but exceptions are being silenced because of #10; can you apply that patch and report back?

**Comment by DaKnOb** [comment]
Yup, there seems to be an exception:
```
Traceback (most recent call last):
  File "check_https.py", line 208, in <module>
    main()
  File "check_https.py", line 194, in main
    data = check_sites()
  File "check_https.py", line 169, in check_sites
    f.result()
  File "/usr/lib/python3.2/concurrent/futures/_base.py", line 393, in result
    return self.__get_result()
  File "/usr/lib/python3.2/concurrent/futures/_base.py", line 352, in __get_result
    raise self._exception
  File "/usr/lib/python3.2/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "check_https.py", line 60, in check_one_site
    context.check_hostname = True
AttributeError: 'SSLContext' object has no attribute 'check_hostname'
```

**Comment by alex** [comment]
Yeah, I think the answer is "this requires Python 3.4"

**Comment by DaKnOb** [comment]
Yeah, probably yes. Didn't see a comment in the first line of the file indicating the interpreter..
